### ISSUE TITLE
Alienate demo don't work well

### ISSUE THREAD

**Issue by mabrilG** [MiSTer-devel/ZX-Spectrum_MISTer#10]
I try this demo in serveral configurations but allways crash after the clean screen effect, in original hardware work correctly. 
On the other hand, the sound with 'General Sound' configuration don't work.

Can download and try it here:
http://www.pouet.net/prod.php?which=10531

Thanks for all the work done to make this perfect core.

**Comment by adrianlongland** [comment]
Running the file linked at the top of that page:
http://www.zxdemo.org/f/200308/alienate_tap.zip
on zxsp, running on a MacBook, it crashes at the same place.
Assuming you mean just before this time:
https://youtu.be/Ee_mszc4kjA?t=47
?

**Comment by mabrilG** [comment]
> Running the file linked at the top of that page:
> http://www.zxdemo.org/f/200308/alienate_tap.zip
> on zxsp, running on a MacBook, it crashes at the same place.
> Assuming you mean just before this time:
> https://youtu.be/Ee_mszc4kjA?t=47
> ?

Yes, Mister core crashes in the same place, after the image change. Fail restarting the spectrum with a constant sound.

**Comment by adrianlongland** [comment]
With a breakpoint at $0773, I can see it is trying to load "alien12" but none of the blocks in the .tap are "alien12". There is "alien0", "alien1" etc. through "alien5".
After the wipe finishes at $07c5a, it pages in bank 6 at $c000, and jumps to $cd9d - but it's all zeros since "alien12" was not loaded, and it crashes.
I tried the various options, Pentagon and Scorpion - plus the Gen Sound - but all try to load "alien12".

In original hardware, what configuration is known to work - and how was the .tap file played back?

**Comment by gyurco** [comment]
The demo should work in USR0 mode, not by loading via the "Tape Loader" option in the main menu.

**Comment by mabrilG** [comment]
> In original hardware, what configuration is known to work - and how was the .tap file played back?
In original hardware I use setting: timings (Spectrum) and music (AY chip). The .tap file have been loaded with DivIDE and esxDOS.

**Comment by sorgelig** [comment]
Demo works fine. At least in latest release.
1) Set ULA-128 and Spectrum 128K/+2 in settings.
2) load the tap.
3) press F10 (same as USR0)
4) in menu of demo choose "Spectrum" mode.

**Comment by mabrilG** [comment]
Thanks to everyone! With F10 (USR 0) mode the demo work perfect.

I close the issue.
